# MySQL DB config
spring:
  datasource:
    url: jdbc:mysql://root:WPBnUtZ5T28PFMZAyMsD@containers-us-west-91.railway.app:6862/railway
    hikari:
      maximum-pool-size: 2
  jackson:
    serialization:
      indent_output: true
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


