# MySQL DB config
spring:
  datasource:
    url: jdbc:${MYSQL_URL}
    hikari:
      maximum-pool-size: 2
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  jackson:
    serialization:
      indent_output: true
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: {gmail_username}
    password: {gmail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


